name: Deploy Azure Function

on:
  push:
    branches: [ main ]
    paths:
      - 'new_backend/followup_scheduler/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd new_backend/followup_scheduler
        pip install -r requirements.txt
        
    - name: Create deployment package
      run: |
        cd new_backend/followup_scheduler
        zip -r followup_scheduler.zip . -x "*.git*" "*.pyc" "__pycache__/*"
        
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'smart-email-functions'
        package: 'new_backend/followup_scheduler/followup_scheduler.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} 
